name: CI
on:
  push:
jobs:
  build:
    name: Multisite Drupal Standard
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme_default: [ec_europa]
        behat_part: [0]
        # theme_default: [ec_resp, ec_europa]
        # behat_part: [0, 1, 2, 3]
        include:
          - theme_default: ec_resp
            behat_part: '0'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_resp
            behat_part: '1'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_resp
            behat_part: '2'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_resp
            behat_part: '3'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '0'
            behat_profile: default
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '1'
            behat_profile: default
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '2'
            behat_profile: default
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '3'
            behat_profile: default
            platform_profile: multisite_drupal_standard
    container:
      image: fpfis/httpd-php-ci:5.6
      env:
        DOCUMENT_ROOT: /test/platform
    services:
      mysql:
        image: percona/percona-server:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      selenium:
        image: wernight/phantomjs
        env:
          DISPLAY: ':99'
          SE_OPTS: '-debug'
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Site build
      run: |
        php --version
        composer install --ansi --no-suggest --no-progress
        ./bin/phing build-platform-dev -propertyfile 'build.properties.drone' -D'platform.profile.name'='${{ matrix.platform_profile }}' -D'platform.site.theme_default'='${{ matrix.theme_default }}'
        ./bin/phing setup-drone-file-system -propertyfile 'build.properties.drone' -D'platform.profile.name'='${{ matrix.platform_profile }}' -D'platform.site.theme_default'='${{ matrix.theme_default }}'
        ./bin/phing install-platform  -propertyfile 'build.properties.drone' -D'platform.profile.name'='${{ matrix.platform_profile }}' -D'platform.site.theme_default'='${{ matrix.theme_default }}'
    # - name: PHPCS
    #   run: |
    #     ./bin/phpcs
    #   if: matrix.code_compliance == 1
    # - name: PHP Unit
    #   run: |
    #     ./bin/phpunit -c tests/phpunit.xml
    #   if: matrix.code_compliance == 1
    - name: Behat
      run: |
        ./bin/behat -c build/tests/balancer/behat.${{ matrix.behat_profile}}.${{ matrix.behat_part }}.yml -p ${{ matrix.behat_profile}} --colors -f pretty --strict
