name: CI
on:
  push:
jobs:
  build:
    name: Multisite Drupal Standard
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme_default: [ec_europa]
        behat_part: [0]
        # theme_default: [ec_resp, ec_europa]
        # behat_part: [0, 1, 2, 3]
        include:
          - theme_default: ec_resp
            behat_part: '0'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_resp
            behat_part: '1'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_resp
            behat_part: '2'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_resp
            behat_part: '3'
            behat_profile: standard_ec_resp
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '0'
            behat_profile: default
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '1'
            behat_profile: default
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '2'
            behat_profile: default
            platform_profile: multisite_drupal_standard
          - theme_default: ec_europa
            behat_part: '3'
            behat_profile: default
            platform_profile: multisite_drupal_standard
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Docker Compose Up
      run: |
        docker-compose up -d
        docker-compose ps
        sleep 10
        docker-compose logs selenium
        docker-compose logs web
    - name: Composer install
      run: |
        docker-compose exec -T web composer install --ansi --no-suggest --no-progress
    - name: Build Platform
      run: |
        docker-compose exec -T web ./bin/phing build-platform-dev -propertyfile 'build.properties.github' -D'platform.profile.name'='${{ matrix.platform_profile }}' -D'platform.site.theme_default'='${{ matrix.theme_default }}'
    - name: Install Platform
      run: |
        docker-compose exec -T web ./bin/phing setup-drone-file-system -propertyfile 'build.properties.github' -D'platform.profile.name'='${{ matrix.platform_profile }}' -D'platform.site.theme_default'='${{ matrix.theme_default }}'
        docker-compose exec -T web ./bin/phing install-platform  -propertyfile 'build.properties.github' -D'platform.profile.name'='${{ matrix.platform_profile }}' -D'platform.site.theme_default'='${{ matrix.theme_default }}'
    - name: Behat
      run: |
        timeout 5m docker-compose exec -T web ./bin/behat -c build/tests/balancer/behat.${{ matrix.behat_profile}}.${{ matrix.behat_part }}.yml -p ${{ matrix.behat_profile}} --colors -f pretty --strict
    - name: Docker Compose Down
      run: |
        docker-compose logs selenium
        docker-compose down